config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount ActionCable.server => '/cable'
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }
  resources :challenges do
    resources :members, only: [:create, :update, :destroy]
    post 'accept_request', to: 'members#accept_request'
    get 'invite', on: :member
    post 'send_invite', on: :member
    get 'voting', on: :member
    get 'send_vote', on: :member
    post 'request_invite'
    resources :challenge_messages, only: [:create]
  end
  post 'deny_request/:id', to: 'challenge_requests#destroy'
  resources :challenge_requests, only: [:index, :destroy]
  root to: 'pages#home'
  get 'dashboard', to: "dashboard#index"
  get 'explore', to: "challenges#index"
end

app/models/challenge_message.rb
class ChallengeMessage < ApplicationRecord
  belongs_to :member
end

app/controllers/challenge_messages_controller.rb
class ChallengeMessagesController < ApplicationController

  def create
    @challenge = Challenge.find(params[:challenge_id])
    @members = Member.where(user_id: current_user.id, challenge_id: params[:challenge_id], inative: false)
    @message = ChallengeMessage.new(challengemessage_params)
    @message.member_id = @members.first.id
    authorize @message
    if @message.save
      respond_to do |format|
        format.html { redirect_to challenge_path(@challenge) }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
      end
    else
      respond_to do |format|
        format.html { render 'challenges/show' }
        format.js  # <-- idem
      end
    end
  end

  private

  def challengemessage_params
    params.require(:challenge_message).permit(:message)
  end
end

app/helpers/challenge_messages_helper.rb
module ChallengeMessagesHelper
end

app/views/challenge_messages/_form.html.erb
<%#= simple_form_for(@challenge_message,url: challenge_challenge_messages_path(@challenge.id), remote: false) do |f| %>
  <%#= f.input :message, label: "Trash Talking", input_html: {id: "chat_speaker_input"} %>
  <%#= f.button :submit, value: "Send", class: "btn btn-primary", 'data-behavior': "chat_speaker" %>
<%# end %>
<form>
  <div class="form-group">
    <textarea  id="chat_speaker_member_txt" data-behavior="chat_speaker" cols="10" rows="5" class="form-control" placeholder="Write a text or input an youtube link"></textarea>
  </div>
  <div class="form-group">
    <input type="hidden" id="chat_speaker_member_id" value="<%= @current_member.id %>">
    <input type="hidden" id="chat_speaker_current_id" value="<%= current_user.id %>">
    <input type="button" id="chat_speaker_member_button" value="Send" class="btn btn-primary btn-block">
  </div>
</form>

app/views/challenge_messages/_show.html.erb
<% unless current_user.nil? %>
  <% if message.member.user.id == current_user.id %>
    <div class="message">
  <% else %>
    <div class="message invert">
  <% end %>
    <p class="balloon">
      <span class="author"><%= Member.find(message.member_id).user.name %>
        <span class="time"> ~ <%= (ChallengeMessage.find(message.id).created_at).strftime("%m/%d/%Y at %H:%M") %> ~ </span>
      </span>

      <% yt_regexp = /^https:\/\/www\.youtube\.com\/watch\?v=([a-zA-Z0-9_-]*)/ %>
      <% yt_valid_link =  (message.message).gsub(/\/watch\?v=/, '/embed/')  %>
      <% img_regexp = /\Ahttp.*(jpeg|jpg|gif|png)\Z/ %>
      <% if (message.message =~ yt_regexp) == 0 %>
        <iframe width="300" height="180" src="<%= yt_valid_link %>" frameborder="0" allowfullscreen style="margin-top: 6px;"></iframe>
      <% elsif (message.message =~ img_regexp) != nil %>
        <img src="<%= message.message %>" alt="" width="300" >
      <% else %>
        <%= message.message %>
      <% end %>

   </p>
   <% unless Member.find(message.member_id).user.picture.url.nil? %>
    <%=image_tag Member.find(message.member_id).user.picture.url(:bright_face), class: "avatar" %>
   <% end %>
  </div>
<% end %>

app/views/challenge_messages/create.js.erb
<% if @challenge_messages.errors.any? %>
  $('#new_message').html("<%= j render 'challenge_messages/form', challenge: @challenge, challengemessages: @challenge_message %>");
<% else %>
  var new_review = $("<%= j render 'challenge_messages/show', challengemessages: @challenge_message %>").hide();
  $('#messages').append(new_review);
  new_review.slideDown();
  $('#new_message').html("<%= j render 'challenge_messages/form', challenge: @challenge, challengemessages: ChallengeMessage.new %>");
<% end %>