config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount ActionCable.server => '/cable'
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }
  resources :challenges do
    resources :members, only: [:create, :update, :destroy]
    post 'accept_request', to: 'members#accept_request'
    get 'invite', on: :member
    post 'send_invite', on: :member
    get 'voting', on: :member
    get 'send_vote', on: :member
    post 'request_invite'
    resources :challenge_messages, only: [:create]
  end
  post 'deny_request/:id', to: 'challenge_requests#destroy'
  resources :challenge_requests, only: [:index, :destroy]
  root to: 'pages#home'
  get 'dashboard', to: "dashboard#index"
  get 'explore', to: "challenges#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-6">
        <ul class="list-inline">
          <li><a href=""><i class="fa fa-youtube"></i></a></li>
          <li><a href=""><i class="fa fa-instagram"></i></a></li>
          <li><a href=""><i class="fa fa-facebook"></i></a></li>
          <li><a href=""><i class="fa fa-twitter"></i></a></li>
        </ul>
      </div>
      <div class="col-xs-12 col-md-6 text-right">
        <p>If it doesn't challenge you, it doesn't change you.</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed-top">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <strong>Challenge</strong>Accepted
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>
      <%=link_to raw('<i class="fa fa-search"></i> Explore'), explore_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <!-- Profile picture and dropdown -->
      <a href="<%= challenge_requests_path %>" class="navbar-wagon-item">
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-red"><%= all_users_request(current_user) %></div>
          <div class="badge2 badge-blue"><%= @waiting_aproval %></div>
        </div>
      </a>
      <p><strong>Game on</strong>, <%= current_user.name %></p>
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= generate_profile_image(current_user) %>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to dashboard_path do %>
                <i class="fa fa-line-chart"></i>  <%= t(".dashboard", default: "Dashboard") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>
      <%=link_to raw('<i class="fa fa-search"></i> Explore'), explore_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <!-- Login text link -->
      <%= link_to raw('<i class="fa fa-user-o"></i> Login'), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
    <% if user_signed_in? %>
      <%= generate_profile_image(current_user) %>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if user_signed_in? %>
          <li class="game-on">
            <p><strong>Game on</strong>, <%= current_user.name %></p>
          </li>
          <li>
            <%= link_to edit_user_registration_path do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%=link_to raw('<i class="fa fa-search"></i> Explore'), explore_path, class: "navbar-wagon-item navbar-wagon-link" %>
          </li>
        <% else %>
          <li><%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <% end %>
        <li>
          <%= link_to "#{all_users_request(current_user)} Requests", challenge_requests_path %></li>
        <li>
          <%= link_to dashboard_path do %>
            <i class="fa fa-line-chart"></i>  <%= t(".dashboard", default: "Dashboard") %>
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    <% else %>
      <div class='logout-only-mobile'>
        <%=link_to raw('<i class="fa fa-user-circle "></i>'), new_user_session_path %>
        <%=link_to raw('<i class="fa fa-search"></i>'), explore_path %>
      </div>
    <% end %>
    </div>
  </div>
  <!-- END: Dropdown list appearing on mobile only -->

</div>