config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount ActionCable.server => '/cable'
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }
  resources :challenges do
    resources :members, only: [:create, :update, :destroy]
    post 'accept_request', to: 'members#accept_request'
    get 'invite', on: :member
    post 'send_invite', on: :member
    get 'voting', on: :member
    get 'send_vote', on: :member
    post 'request_invite'
    resources :challenge_messages, only: [:create]
  end
  post 'deny_request/:id', to: 'challenge_requests#destroy'
  resources :challenge_requests, only: [:index, :destroy]
  root to: 'pages#home'
  get 'dashboard', to: "dashboard#index"
  get 'explore', to: "challenges#index"
end

app/views/pages/_cards.html.erb
<div class="wrapper-cards">
  <div class="container">
    <h3 class='home-title-type'>
      <i class="fa fa-group"></i>
      Group Challenges
    </h3>
    <div class="row your-class">

      <% Challenge.where(yourself: false).sample(4).each do |challenge| %>
        <% unless challenge.yourself %>
          <div class="col-sm-6 col-md-6 col-lg-3">
            <div class="card">
              <div class="card-picture">
                <% if challenge.picture.url %>
                  <%=image_tag challenge.picture.url(:thumb) %>
                <% else %>
                  <div class="no-img"><i class="fa fa-image"></i></div>
                <% end %>
              </div>
               <div class="card-desc text-center">
                <h4>
                  <%= challenge.title %>
                </h4>
              </div>
              <%=link_to challenge.title, challenge_path(challenge), class: "card-link" %>
            </div>
          </div>
        <% end %>
      <% end %>

    </div>
  </div>
</div>

<div class="wrapper-cards-self">
  <div class="container">
    <h3 class='home-title-type'>
      <i class="fa fa-user"></i>
      Self Challenges
    </h3>
    <div class="row your-class">

      <% @self_challenges.each do |challenge| %>
        <% if challenge.yourself %>
          <div class="col-sm-6 col-md-6 col-lg-3">
            <div class="card">
              <div class="card-picture">
                <% if challenge.picture.url %>
                  <%=image_tag challenge.picture.url(:thumb) %>
                <% else %>
                  <div class="no-img"><i class="fa fa-image"></i></div>
                <% end %>
              </div>
               <div class="card-desc text-center">
                <h4>
                  <%= challenge.title %>
                </h4>
              </div>
              <%=link_to challenge.title, challenge_path(challenge), class: "card-link" %>
            </div>
          </div>
        <% end %>
      <% end %>

    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class='banner banner-home banner-with-video'>
  <div id="player"></div>
  <div class="shadow"></div>
  <div class='container'>
    <div class='banner-content'>
      <div>
        <h1>Challenge your friends</h1>
        <p><strong>Motivate each other :)</strong></p> <br>
        <%=link_to raw('<i class="fa fa-flag"></i> Start a challenge'), new_challenge_path, class: "btn-create btn-lg" %>
      </div>
    </div>
  </div>
</div>

<div class='container home-text'>
  <h2>Staff picks <i class="fa fa-heart"></i></h2>
</div>

<%= render 'cards' %>

<div class='container'>
  <h2 class="home-text">
    How it works <i class="fa fa-gears"></i>
  </h2>
  <hr>
  <div class='row text-center how-it-works'>
    <div class='col-xs-12 col-sm-6 col-md-4'>
      <%= image_tag("Idea-150.png", size: "150x150") %>
      <h3>Come up with a challenge</h3>
      <p>Or ask to join one</p>
    </div>
    <div class='col-xs-12 col-sm-6 col-md-4'>
      <%= image_tag("friends2.jpg", size: "150x150", class: "img-circle") %>
      <h3>Invite your friends</h3>
      <p></p>
    </div>
    <div class='col-xs-12 col-sm-6 col-md-4'>
      <%= image_tag("heart.png") %>
      <h3>Share and Love</h3>
      <p>Discover what's new and be part of it </p>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    var tag = document.createElement('script');

    tag.src = "https://www.youtube.com/iframe_api";
    var firstScriptTag = document.getElementsByTagName('script')[0];
    firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

    var player;
    function onYouTubeIframeAPIReady() {
      player = new YT.Player('player', {
        videoId: 'NugRZGDbPFU',
        width: 1280,
        height: 800,
        playerVars: { 'autoplay': 1, 'controls': 0, 'loop': 1, 'rel': 0 },
        events: {
          'onReady': onPlayerReady,
        }
      });
    }

    function onPlayerReady(event) {
      event.target.playVideo();
      event.target.mute();
    }

    $(function() {

      // Find all YouTube videos
      var $allVideos = $("iframe[src^='//www.youtube.com']"),

          // The element that is fluid width
          $fluidEl = $(".banner-with-video");

      // Figure out and save aspect ratio for each video
      $allVideos.each(function() {

        $(this)
          .data('aspectRatio', this.height / this.width)

          // and remove the hard coded width/height
          .removeAttr('height')
          .removeAttr('width');

      });

      // When the window is resized
      // (You'll probably want to debounce this)
      $(window).resize(function() {

        var newWidth = $fluidEl.width();

        // Resize all videos according to their own aspect ratio
        $allVideos.each(function() {

          var $el = $(this);
          $el
            .width(newWidth)
            .height(newWidth * $el.data('aspectRatio'));

        });

      // Kick off one resize to fix all videos on page load
      }).resize();

    });

  <% end %>
<% end %>