config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount ActionCable.server => '/cable'
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }
  resources :challenges do
    resources :members, only: [:create, :update, :destroy]
    post 'accept_request', to: 'members#accept_request'
    get 'invite', on: :member
    post 'send_invite', on: :member
    get 'voting', on: :member
    get 'send_vote', on: :member
    post 'request_invite'
    resources :challenge_messages, only: [:create]
  end
  post 'deny_request/:id', to: 'challenge_requests#destroy'
  resources :challenge_requests, only: [:index, :destroy]
  root to: 'pages#home'
  get 'dashboard', to: "dashboard#index"
  get 'explore', to: "challenges#index"
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  belongs_to :owner, foreign_key: "id_user_owner", class_name: "User"
  has_many :members
  has_many :users, through: :members
  has_many :members
  has_many :invites
  has_many :challenge_requests
  has_many :challenge_messages, through: :members
  accepts_nested_attributes_for :invites, reject_if: :all_blank, allow_destroy: true
  mount_uploader :picture, PhotoUploader
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_challenge, only: [:show, :edit, :update, :destroy, :invite, :send_invite, :voting, :send_vote]
  before_action :set_members, only: [:show, :voting]

  def index
    @challenges = policy_scope(Challenge)
  end

  def show
    @challenge.end_date = 0 if @challenge.end_date.nil?
    status_total = (@challenge.end_date - @challenge.start_date).to_i
    status_until_now = (Date.today - @challenge.start_date).to_i
    @status_percentage = (status_until_now * 100)/status_total
    @status_percentage = 100 if @status_percentage > 100
    @status_percentage = 0 if @status_percentage < 0
    @status_days_to_finish = ((status_total - status_until_now) < 0) ? 0 : status_total - status_until_now
    @status_days_to_start  = (@challenge.start_date - Date.today).to_i

    @challenge_message = ChallengeMessage.new

    if current_user.present?
      @current_member = Member.where(challenge_id: @challenge.id, user_id: current_user.id).last
    end
    user_challenge_messages = []
    Member.where(challenge_id: @challenge.id).each do |member|
      user_challenge_messages << ChallengeMessage.where(member_id: member.id)
    end
    @challenge_messages = user_challenge_messages.flatten.sort_by { |k| k[:created_at] }
  end

  def new
    @challenge = Challenge.new
    authorize @challenge
  end

  def create
    @challenge = Challenge.new(challenge_params)
    @challenge.owner = current_user
    authorize @challenge
    if @challenge.save
      members = Member.new
      members.user_id = current_user.id
      members.challenge_id = @challenge.id
      if members.save
        redirect_to challenge_path(@challenge)
      else
        render :new
      end
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @challenge.update(challenge_params)
      flash[:notice] = "There you go! Your challenge is now updated."
      redirect_to challenge_path(@challenge)
    else
      render :edit
    end
  end

  def destroy
    @challenge.destroy
    redirect_to challenges_path
  end

  def invite
    authorize @challenge
    @challenge.invites.build
    #this action generates the file
  end

  def send_invite
    InviteMailer.welcome(@challenge, @challenge.invites).deliver_now
    #redirect_to challenge_url(challenge.id)
  end

  def voting
    @winner2 = @members.each_with_object(Hash.new(0)) { |h1, h2| h2[h1[:voted_id]] += 1 }
    @winner  = @members.each_with_object(Hash.new(0)) { |h1, h2| h2[h1[:voted_id]] += 1 }
    @winner  = @winner.key(@winner.values.max)
    @winner  = User.find(@winner) if @winner != nil
  end

  def send_vote
    member = Member.where(user_id: params[:user_id], challenge_id: params[:id])
    member = member[0]
    unless member_voted?(member)
      member.voted_id = params[:voted_user_id].to_i
      member.save
      flash[:notice] = "Your vote has been confirmed!"
    else
      flash[:alert] = "You already voted!"
    end
    redirect_to challenge_path(@challenge.id)
  end

  def request_invite
    @request = ChallengeRequest.where(user_id: current_user.id,
                                 challenge_id: params[:challenge_id])
    if @request.empty?
      @request = ChallengeRequest.create(user_id: current_user.id,
                                    challenge_id: params[:challenge_id])
      flash[:notice] = "Your request was sent."
    else
      flash[:alert] = "You have already requested it."
    end
    authorize @request
    redirect_to challenge_path(params[:challenge_id])
  end

  private

  def member_voted?(member)
    member.voted_id.present?
  end

  def set_members
    @members = @challenge.members.where(inative: false)
  end

  def set_challenge
    @challenge = Challenge.find(params[:id])
    authorize @challenge
  end

  def challenge_params
     params.require(:challenge).permit(:title, :description, :rules, :at_stake, :picture, :start_date, :end_date, :id_user_owner, :picture_cache, :voted_user_id, :member_id, invites_attributes: [:guest_email])
  end
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/_about.html.erb
<div class="container">
  <div class="row col-sm-6 col-sm-offset-3">
    <p class="text-center"><%= h(@challenge.description).gsub(/\n/, '<br/>').html_safe %></p>
    <p class="text-center"><strong>Rules:</strong></p>
    <p class="text-center"><%= @challenge.rules %></p>
    <p class="text-center"><strong>At Stake:</strong></p>
    <p class="text-center"><%= @challenge.at_stake %></p>
  </div>
</div>

app/views/challenges/_action_bar.html.erb
<div class="wrapper-action-bar">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 text-center">
        <% if !signed_in? %>
          <p>You're not logged... :(</p>
          <%= link_to raw('<i class="fa fa-user-o"></i> Login'), new_user_session_path, class: 'btn btn-primary' %>
        <% else %>
          <% if Member.where(user_id: current_user.id, challenge_id: @challenge.id).empty? %>
            <% if (@challenge.invites.where(guest_email: current_user.email)).empty? %>
              <p>You're not invited... :(</p>
              <%= link_to "Request to join", challenge_request_invite_path(@challenge), method: :post,
                          class: 'btn btn-success' if @status_percentage.to_i < 100 %>
            <% else %>
              <%= button_to "Accept Challenge", challenge_members_path(@challenge), method: :post, class: 'btn btn-lg btn-success btn-block'%>
            <% end %>
          <% else %>
            <% if !Member.where(user_id: current_user.id, challenge_id: @challenge.id, inative: true).empty? %>
              <p>You cannot re-join to this challenge... :(</p>
            <% else %>
              <%= link_to "Invite friends", invite_challenge_path, :class => "btn btn-lg btn-success" if @status_percentage.to_i < 100 %>
              <%= link_to "It is time to vote", voting_challenge_path(@challenge.id), class: "btn btn-lg btn-warning" if @status_percentage.to_i >= 100 %>
              <%= link_to "Leave",
                          challenge_member_path( @challenge.id,
                                                 Member.where(user_id: current_user.id,
                                                         challenge_id: @challenge.id).first.id),
                          method: :PATCH, data: { confirm: "Are you sure?" },
                          class: "btn btn-lg btn-danger" if (@status_percentage.to_i < 100) && (@challenge.owner != current_user)
              %>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/challenges/_form.html.erb
<%= simple_form_for(@challenge) do |f| %>
  <%= f.error_notification %>
  <%= f.input :title, placeholder: 'Ex: Ice Bucket challenge' %>
  <%= f.input :description, placeholder: 'Within 24 hours of being challenged, participants have to record a video of themselves in continuous footage...', input_html: {rows: 3} %>
  <%= f.input :rules, placeholder: 'The bucket has to be filled with ice! Don\'t do it with just water', input_html: {rows: 3} %>
  <%= f.input :at_stake, placeholder: 'Ex: Nothing, or $30 each for the winner, or whoever wins get to choose lunch place for a week or whatever you decide' %>
  <%= f.input :picture, input_html: {class:'custom-file-input'} %>
  <%= f.input :picture_cache, as: :hidden %>
  <div class="row">
    <div class="col-sm-6 form-space-bottom">
      <label class="control-label string optional" for="challenge_start_date">Start date</label>
      <div class="input-group date">
        <%= f.input :start_date, as: :string, input_html: {class:'datepicker'}, label: false %>
        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
      </div>
    </div>
    <div class="col-sm-6 form-space-bottom">
      <label class="control-label string optional" for="challenge_end_date">End date</label>
      <div class="input-group date">
        <%= f.input :end_date, as: :string, input_html: {class:'datepicker'}, label: false %>
        <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
      </div>
    </div>
  </div>
  <div class="bottom-links">
    <%= f.button :submit, class: "btn-primary btn-lg btn-block" %>
  </div>
<% end %>

app/views/challenges/_invite_fields.html.erb
<div class='nested-fields text-center' style='display: inline;'>
  <p style="float:right;">
    <%= f.input :guest_email, placeholder: 'email', label: false %>
    <%= link_to_remove_association "Remove", f , class: 'invite glyphicon glyphicon-remove-circle', style:"color:red;" %>
  </p>
</div>

app/views/challenges/_messages.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-6 col-md-offset-3">
    <% if Member.where(challenge_id: @challenge.id, user_id: current_user.id, inative: true).empty? %>
      <div id="messages">
        <div class="messages-wrapper">
          <% if @challenge_messages.blank? %>
            The trash talk for <%= @challenge.title %> starts here.
          <% else %>
            <% @challenge_messages.each do |message| %>
              <%= render 'challenge_messages/show', message: message %>
            <% end %>
          <% end %>
        </div>
      </div>
      <%= render 'challenge_messages/form' %>
    <% else %>
      <p class='text-center'>You cannot see the challenge messages...  =/</p>
    <% end %>
  </div>
</div>

app/views/challenges/_self_action_bar.html.erb
<div class="wrapper-action-bar">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 text-center">
        <% if !signed_in? %>
          <p>You're not logged... :/</p>
          <%= link_to raw('<i class="fa fa-user-o"></i> Login'), new_user_session_path, class: 'btn btn-primary' %>
        <% else %>
          <% if Member.where(user_id: current_user.id, challenge_id: @challenge.id).empty? %>
            <%= link_to "Join", challenge_members_path(@challenge), method: :post, class: 'btn btn-success' %>
          <% else %>
            <%= link_to "Leave",
                        challenge_member_path( @challenge.id,
                                               @challenge.members.find_by(user_id: current_user) ),
                        method: :delete,
                        data: { confirm: "Are you sure?" },
                        class: "btn btn-lg btn-danger"
            %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/challenges/_status_bar.html.erb
<div class="wrapper-progress-bar">
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <div class="progress">
          <% color = "progress-bar-success" if @status_percentage.to_i  >= 100 %>
          <% color = "progress-bar-primary" if (@status_percentage.to_i >= 75 && @status_percentage.to_i < 100) %>
          <% color = "progress-bar-primary" if (@status_percentage.to_i >= 50 && @status_percentage.to_i < 75)  %>
          <% color = "progress-bar-warning" if (@status_percentage.to_i >= 25 && @status_percentage.to_i < 50)  %>
          <% color = "progress-bar-danger"  if @status_percentage.to_i  <  25  %>

          <div class="progress-bar <%=color%> progress-bar-striped active" role="progressbar" aria-valuenow="<%= @status_percentage %>" aria-valuemin="0" aria-valuemax="100" style="width: <%= @status_percentage %>%;">
            <span><%= @status_percentage %>% Complete</span>
          </div>
        </div>
      </div>
      <div class="col-sm-6 text-center">
        <ul class="list-inline progress-bar-info">
          <li class="text-left">
            <% if @status_days_to_start > 0 %>
              <strong><%= @status_days_to_start %></strong>
              <br>
              Days to start
            <% else %>
              <strong class="ended"><%= (@status_days_to_finish == 0) ? 'Finished' : @status_days_to_finish %></strong>
              <br>
              Days to finish
            <% end %>
          </li>
          <li class="text-left">
            <strong><%= @challenge.members.count %></strong> <br>
            Member(s)
          </li>
          <li class="date text-left">
            <strong><%= (@challenge.start_date).strftime("%d/%m/%y") %></strong> <br>
            Start date
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/challenges/_tabs.html.erb
<div class="bg-white">
  <div class="container">
    <div class="row tabs">
      <input type="button" id="about"   class="tab col-xs-4 col-sm-4 col-md-2 col-md-offset-3" value="About">
      <input type="button" id="message" class="tab col-xs-4 col-sm-4 col-md-2 active" value="Trash talk">
      <input type="button" id="members" class="tab col-xs-4 col-sm-4 col-md-2" value="Members">
    </div>
  </div>
</div>

<div class="wrapper-tabs bg-light-gray">
  <div class="container">
    <div class="tab-about tab-invisible">
      <%= render 'about' %>
    </div>
    <div class="tab-message">
      <% if signed_in? %>
        <% unless @challenge.users.where(id: current_user.id).empty? %>
          <%= render 'messages' %>
        <% else %>
          <p class='text-center'>You are not allowed :( </p>
        <% end %>
      <% else %>
        <p class='text-center'>You are not allowed :( </p>
      <% end %>
    </div>
    <div class="tab-members tab-invisible">
      <% if signed_in? %>
        <%= render 'members' %>
      <% else %>
        <p class="text-center">
          <%= Member.where(challenge_id: params[:id]).count %>
          <%= (Member.where(challenge_id: params[:id]).count) == 1 ? 'Member' : 'Members'%>
          in this challenge
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/challenges/edit.html.erb
<div class="container">
  <h1>Edit</h1>
  <div class="padded">
    <%= simple_form_for(@challenge) do |f| %>
      <%= f.error_notification %>
      <%= f.input :title, placeholder: 'Ex: Ice Bucket challenge' %>
      <%= f.input :description, placeholder: 'Within 24 hours of being challenged, participants have to record a video of themselves in continuous footage...', input_html: {rows: 3} %>
      <%= f.input :rules, placeholder: 'Within 24 hours of being challenged, participants have to record a video of themselves in continuous footage...', input_html: {rows: 3} %>
      <%= f.input :picture %>
      <%= f.input :picture_cache, as: :hidden %>
      <div class="row">
        <div class="col-sm-6 form-space-bottom">
         <label class="control-label string optional" for="challenge_start_date">Start date</label>
          <div class="input-group date">
            <%= f.input :start_date, as: :string, input_html: {class:'datepicker'}, label: false %>
            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
          </div>
        </div>
        <div class="col-sm-6 form-space-bottom">
          <label class="control-label string optional" for="challenge_end_date">End date</label>
          <div class="input-group date">
            <%= f.input :end_date, as: :string, input_html: {class:'datepicker'}, label: false %>
            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
          </div>
        </div>
      </div>
      <%= f.button :submit %>
    <% end %>
  </div>
</div>

app/views/challenges/index.html.erb
<div class='banner banner-explore'>
  <div class="shadow"></div>
  <div class='banner-content'>
    <div class="container">
      <h1 class='text-center'>Get some inspiration!</h1>
    </div>
  </div>
</div>

<div class="bg-white">
  <div class="container">
    <div class="row tabs tabs-dashboard">
      <input type="button" id="group-challenge"  class="tab col-xs-6 col-sm-6 col-md-4 col-md-offset-2 active" value="group challenges">
      <input type="button" id="self-challenge" class="tab col-xs-6 col-sm-6 col-md-4" value="self challenges">
    </div>
  </div>
</div>

<div class="container">

  <div class='row'>
    <div class='tab-group-challenge'>

      <% @challenges.where(yourself: false).each do |challenge| %>
        <div class="col-sm-6 col-md-4 col-lg-3 text-center">
          <div class='card-explore'>
            <% if challenge.picture %>
              <%= cl_image_tag(challenge.picture, width: 200, height: 200, crop: 'thumb', class: 'card-explore-picture') %>
            <% else %>
              <div class="no-img"><i class="fa fa-image"></i></div>
            <% end %>
            <div class="shadow"></div>
            <%=link_to raw('<span>' + challenge.title + '</span>'), challenge_path(challenge), class: 'card-explore-link' %>
          </div>
        </div>
      <% end %>
    </div>


    <div class='row'>
      <div class='tab-self-challenge  tab-invisible'>

        <% @challenges.where(yourself: true).each do |challenge| %>
          <div class="col-sm-6 col-md-4 col-lg-3">
            <div class='card-explore text-center'>
              <% if challenge.picture %>
                <%= link_to challenge_path(challenge) do %>
                  <%= cl_image_tag(challenge.picture, width: 200, height: 200, crop: 'thumb', class: 'img-circle') %>
                <% end %>
              <% else %>
                <div class="no-img"><i class="fa fa-image"></i></div>
              <% end %><br>
              <%=link_to challenge.title, challenge_path(challenge)%>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/challenges/invite.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h2 class="text-center title_invite">Invite your buddies</h2>
      <div class="invite_field">
        <%= simple_form_for @challenge do |f| %>
          <%= f.simple_fields_for :invites, @challenge.invites.last do |invite| %>
            <%= render 'invite_fields', f: invite %>
          <%end%>
          <p class='text-center'>
            <span style="margin-right: 15px;">
            <%= link_to 'Back', :back, class: 'btn btn-default' %>
            <%= link_to_add_association 'Add', f, :invites, class: 'btn btn-primary' %>
            <%#= f.button :submit,  'Send', class: 'btn btn-success'  %>
            <%= link_to "Send", challenge_path(@challenge), data: { confirm: "Your invitation will be sent" },
                        class: 'btn btn-success'%>
            </span>
          </p>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/challenges/new.html.erb
<div class='container'>
  <div class="row">
    <div class="col-xs-12 col-sm-9 col-sm-offset-1">
      <h1>Go ahead and create your challenge :)</h1>
      <div class="padded">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/challenges/show.html.erb
<% if @challenge.picture.nil? %>
<div class="banner banner-show">
<% else %>
<div class="banner banner-show" style="background-image: url('<%= @challenge.picture.url(:wide) %>')">
<% end %>
  <div class="shadow"></div>
  <div class="banner-content">
    <h1><%= @challenge.title %></h1>
  </div>
</div>
<% if @challenge.yourself %>
  <%= render 'self_action_bar' %>
  <div class="container">
    <p class='text-center'><strong>About</strong></p>
    <%= render 'about' %>
  </div>
<% else %>
  <%= render 'action_bar' %>
  <%= render 'status_bar' %>
  <%= render 'tabs' %>
<% end %>
<%=hidden_field_tag 'current_challenge_id', @challenge.id %>

app/views/challenges/voting.html.erb
<div class="container">
  <div class="row">
    <% if @members.where(challenge_id: @challenge.id, voted_id: nil).empty? %>
      <h3 class="text-center">The winner is</h3>
      <div class ="col-sm-2 col-sm-offset-5 photo-margin text-center">
        <%= generate_profile_photo(@winner) %>
        <br><%= @winner.name %>
      </div>
    <% else %>
      <% unless @members.where(challenge_id: @challenge.id, user_id: current_user.id, voted_id: nil).empty? %>
        <h3 class="text-center">Voting time!</h3>
        <% @members.where(challenge_id: @challenge.id).each do |member| %>
          <div class ="col-sm-2 photo-margin text-center">
            <%= generate_profile_photo(member.user) %>
            <br><%= member.user.name %><br>
            <%= link_to "Vote",
                        send_vote_challenge_path(@challenge, voted_user_id: member.user_id, user_id: current_user.id),
                        data: { confirm: "Vote to #{member.user.name}?" }, class: 'btn btn-primary' %>
          </div>
        <% end %>
      <% else %>
        <h3 class="text-center">Who's gonna win the challenge?</h3>
        <% @members.each do |member| %>
          <div class ="col-sm-2 photo-margin text-center">
            <%= generate_profile_photo(member.user) %>
            <br><%= member.user.name %>
            <br>Votes <%= ( @winner2[member.user_id] * 100.0 / @members.where('voted_id IS NOT NULL').count ).round(2) %>%
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>
<div class="container">
  <div class="row" style="padding-top: 50px">
    <div class="text-left">
      <%= link_to raw("<li class='fa fa-long-arrow-left'></li> Back"), :back, class: 'btn btn-default'%>
    </div>
  </div>
</div>